### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by naon708** [naon708/search_app_rails#27]
```ruby
# NG
dancer = Dancer.all.pluck(:title)
# Fixed
dancer = Dancer.pluck(:title)
```
#### allで全件取得してるのおかしいので修正

```ruby
# NG
Processing by Api::V1::AutocompletesController#index as */*
   (1.4ms)  SELECT "programs"."japanese_notation" FROM "programs"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:3:in `index'
   (36.6ms)  SELECT "dancers"."title" FROM "dancers"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:4:in `index'
   (2.9ms)  SELECT "steps"."japanese_notation" FROM "steps"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:5:in `index'
   (3.5ms)  SELECT "variations"."title" FROM "variations"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:6:in `index'
```

```ruby
# Fixed
Processing by Api::V1::AutocompletesController#index as */*
   (0.3ms)  SELECT "programs"."japanese_notation" FROM "programs"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:3:in `index'
   (0.3ms)  SELECT "dancers"."title" FROM "dancers"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:4:in `index'
   (0.4ms)  SELECT "steps"."japanese_notation" FROM "steps"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:5:in `index'
   (0.3ms)  SELECT "variations"."title" FROM "variations"
  ↳ app/controllers/api/v1/autocompletes_controller.rb:6:in `index'
```

**Comment by naon708** [comment]
https://railsguides.jp/active_record_querying.html#pluck
